from pathlib import Path
import sys

import streamlit as st

ROOT_DIR = Path(__file__).resolve().parent
SRC_DIR = ROOT_DIR / "src"
sys.path.append(str(SRC_DIR))

from load_data import load_torvik_four_factors, get_team
from matchup import generate_matchup_report

st.set_page_config(
    page_title="Illini Opponent Prep",
    page_icon="🏀",
    layout="wide",
)

@st.cache_data
def load_data():
    """
    Load Four Factors data and cache it

    Streamlit reruns the whole file when changes occur, so this prevents unnecessary re-downloading
    """
    return load_torvik_four_factors(2026)

def write_bullet_section(title: str, items: list[str], empty_message: str):
    """
    Display a report section with bullet points
    
    If list is empty, show fallback message
    """
    st.subheader(title)

    if len(items) == 0:
        st.write(f"- {empty_message}")
        return
    for item in items:
        st.write(f"- {item}")

four_factors = load_data()

st.title("Illinois Men's Basketball Opponent Prep")
st.caption("Opponent scouting dashboard using BartTorvik Four Factors data")

team_names = sorted(four_factors["TeamName"].dropna().unique())

opponent_name = st.selectbox(
    "Choose opponent",
    team_names,
    index=team_names.index("Houston") if "Houston" in team_names else 0,
)

illinois = get_team(four_factors, "Illinois", "TeamName")
opponent = get_team(four_factors, opponent_name, "TeamName")

report = generate_matchup_report(illinois, opponent)

st.divider()

st.header(f"Illinois vs. {report['opponent']}")

left_col, right_col = st.columns(2)

with left_col:
    write_bullet_section(
        "Illinois strengths",
        report["illinois_strengths"],
        "No major Illinois strengths flagged by the current national-threshold model",
    )

    write_bullet_section(
        f"{report['opponent']} weaknesses",
        report["opponent_weaknesses"],
        "No major opponent weaknesses flagged by the current national-threshold model",
    )

st.divider()

write_bullet_section(
    "Opponent danger areas",
    report["opponent_dangers"],
    "No major opponent danger areas flagged by the current rule set",
)

write_bullet_section(
    "Matchup swing factors",
    report["matchup_swing_factors"],
    "No major swing factors generated by the current rule set",
)

write_bullet_section(
    "Keys to victory",
    report["keys_to_victory"],
    "No keys generated by the current rule set",
)