from pathlib import Path
import sys

import pandas as pd
import streamlit as st

ROOT_DIR = Path(__file__).resolve().parent
SRC_DIR = ROOT_DIR / "src"
sys.path.append(str(SRC_DIR))

SEASON_YEAR = 2026

from load_data import load_torvik_four_factors, get_team
from matchup import generate_matchup_report
from metrics import add_percentile_columns

st.set_page_config(
    page_title="Illini Opponent Prep",
    page_icon="🏀",
    layout="wide",
)


@st.cache_data
def load_data():
    """
    Load Four Factors data and cache it

    Streamlit reruns the whole file when changes occur, so this prevents unnecessary re-downloading
    """
    four_factors = load_torvik_four_factors(SEASON_YEAR)
    four_factors = add_percentile_columns(four_factors)

    return four_factors


def write_bullet_section(title: str, items: list[str], empty_message: str) -> None:
    """
    Display a report section with bullet points

    If list is empty, show fallback message
    """
    st.subheader(title)

    if len(items) == 0:
        st.write(f"- {empty_message}")
        return

    for item in items:
        st.write(f"- {item}")


def write_matchup_score_explanation() -> None:
    """
    Explain how base favorability should be interpreted
    """
    with st.expander("How to read base favorability", expanded=False):
        st.write(
            "Base favorability is a 0-100 score from the selected base team's perspective. "
            "Higher is better for the base team. Lower is worse for the base team."
        )

        st.write(
            "For opponent pressure areas, the score compares the base team's resistance metric "
            "against the opponent's attacking metric. For base team edge areas, it compares "
            "the base team's attacking metric against the opponent's resistance metric."
        )

        st.write(
            "A score near 100 means the matchup strongly favors the base team. "
            "A score near 50 is closer to neutral. A score near 0 means the matchup strongly favors the opponent."
        )


def write_supporting_stats_table(rows: list[dict]) -> None:
    """
    Display compact supporting stats behind the matchup engine
    """
    st.subheader("Supporting stats")
    st.caption("Base favorability is always from the selected base team's perspective. Higher is better.")

    if len(rows) == 0:
        st.write("No supporting stats generated by the matchup engine.")
        return

    table = pd.DataFrame(rows)

    base_team_name = table["base_team"].iloc[0]
    opponent_name = table["opponent"].iloc[0]

    base_metric_col = f"{base_team_name} metric"
    base_percentile_col = f"{base_team_name} percentile"
    opponent_metric_col = f"{opponent_name} metric"
    opponent_percentile_col = f"{opponent_name} percentile"

    table = table.rename(
        columns={
            "area": "Area",
            "direction": "Matchup lens",
            "matchup_type": "Type",
            "base_favorability_score": "Base favorability",
            "base_metric_display_name": base_metric_col,
            "base_percentile": base_percentile_col,
            "opponent_metric_display_name": opponent_metric_col,
            "opponent_percentile": opponent_percentile_col,
        }
    )

    table = table[
        [
            "Area",
            "Base favorability",
            "Matchup lens",
            "Type",
            base_metric_col,
            base_percentile_col,
            opponent_metric_col,
            opponent_percentile_col,
        ]
    ]

    st.dataframe(
        table,
        hide_index=True,
        width="stretch",
        column_config={
            "Base favorability": st.column_config.NumberColumn(
                "Base favorability",
                format="%.1f",
            ),
            base_percentile_col: st.column_config.NumberColumn(
                base_percentile_col,
                format="%.1f",
            ),
            opponent_percentile_col: st.column_config.NumberColumn(
                opponent_percentile_col,
                format="%.1f",
            ),
        },
    )


four_factors = load_data()

st.title("Men's Basketball Opponent Prep")
st.caption("Opponent scouting dashboard using BartTorvik Four Factors data")

team_names = sorted(four_factors["TeamName"].dropna().unique())

base_team_name = st.selectbox(
    "Choose base team",
    team_names,
    index=team_names.index("Illinois") if "Illinois" in team_names else 0,
)

opponent_name = st.selectbox(
    "Choose opponent",
    team_names,
    index=team_names.index("Houston") if "Houston" in team_names else 0,
)

base_team = get_team(four_factors, base_team_name, "TeamName")
opponent = get_team(four_factors, opponent_name, "TeamName")

report = generate_matchup_report(base_team, opponent)

st.divider()

st.header(f"{report['base_team']} vs. {report['opponent']}")

st.write(f"**{report['base_team']} identity:** {report['base_team_archetype']}")
st.write(f"**{report['opponent']} identity:** {report['opponent_archetype']}")

st.subheader("Scout summary")
st.write(report["matchup_summary"])

write_matchup_score_explanation()

write_supporting_stats_table(report["supporting_stats"])

st.divider()

left_col, right_col = st.columns(2)

with left_col:
    write_bullet_section(
        "Top opponent pressure areas",
        report["priority_opponent_pressures"],
        "No major opponent pressure areas generated by the percentile matchup engine",
    )

with right_col:
    write_bullet_section(
        f"Top {report['base_team']} edge areas",
        report["priority_base_team_edges"],
        "No major base team edge areas generated by the percentile matchup engine",
    )

st.divider()

write_bullet_section(
    "Keys to victory",
    report["keys_to_victory"],
    "No keys generated by the matchup engine",
)

with st.expander("Supporting legacy context", expanded=False):
    left_col, right_col = st.columns(2)

    with left_col:
        write_bullet_section(
            f"{report['base_team']} strengths",
            report["base_team_strengths"],
            "No major base team strengths flagged by the current national-threshold model",
        )

        write_bullet_section(
            f"{report['base_team']} matchup advantages",
            report["base_team_advantages"],
            "No clear base-team-specific matchup advantages flagged by the current rule set",
        )

    with right_col:
        write_bullet_section(
            f"{report['opponent']} strengths",
            report["opponent_strengths"],
            "No major opponent strengths flagged by the current national-threshold model",
        )

        write_bullet_section(
            f"{report['opponent']} weaknesses",
            report["opponent_weaknesses"],
            "No major opponent weaknesses flagged by the current national-threshold model",
        )

    write_bullet_section(
        "Opponent danger areas",
        report["opponent_dangers"],
        "No major opponent danger areas flagged by the current rule set",
    )

    write_bullet_section(
        "Matchup swing factors",
        report["matchup_swing_factors"],
        "No major swing factors generated by the current rule set",
    )