import sys

SEASON_YEAR = 2026

from load_data import load_torvik_four_factors, get_team
from metrics import add_percentile_columns
from matchup_engine import (
    format_top_opponent_pressures,
    format_top_base_team_edges,
    generate_engine_keys_to_victory,
    generate_matchup_summary,
    identify_team_archetype,
    get_matchup_evidence_rows,
)
from legacy_matchup import (
    get_base_team_advantages,
    get_opponent_dangers,
    get_matchup_swing_factors,
)
from scouting import generate_team_report

def generate_matchup_report(base_team, opponent) -> dict:
    """
    Generate a matchup report comparing the base team to a single opponent
    """
    base_team_report = generate_team_report(base_team)
    opponent_report = generate_team_report(opponent)

    report = {
        "base_team": base_team_report["team"],
        "opponent": opponent_report["team"],
        "base_team_archetype": identify_team_archetype(base_team),
        "opponent_archetype": identify_team_archetype(opponent),
        "matchup_summary": generate_matchup_summary(base_team, opponent),
        "base_team_strengths": base_team_report["strengths"],
        "opponent_strengths": opponent_report["strengths"],
        "opponent_weaknesses": opponent_report["weaknesses"],
        "priority_opponent_pressures": format_top_opponent_pressures(base_team, opponent),
        "priority_base_team_edges": format_top_base_team_edges(base_team, opponent),
        "base_team_advantages": get_base_team_advantages(base_team, opponent),
        "opponent_dangers": get_opponent_dangers(base_team, opponent),
        "matchup_swing_factors": get_matchup_swing_factors(base_team, opponent),
        "keys_to_victory": generate_engine_keys_to_victory(base_team, opponent),
        "supporting_stats": get_matchup_evidence_rows(base_team, opponent),
    }

    return report

def print_section(title: str, items: list[str], empty_message: str) -> None:
    """
    Print a report section if the section has no items, print a fallback message
    """
    print(f"\n{title}")

    if len(items) == 0:
        print("-", empty_message)
        return

    for item in items:
        print("-", item)

if __name__ == "__main__":
    four_factors = load_torvik_four_factors(SEASON_YEAR)
    four_factors = add_percentile_columns(four_factors)

    if len(sys.argv) > 2:
        base_team_name = sys.argv[1]
        opponent_name = " ".join(sys.argv[2:])
    elif len(sys.argv) > 1:
        base_team_name = "Illinois"
        opponent_name = " ".join(sys.argv[1:])
    else:
        base_team_name = "Illinois"
        opponent_name = "Houston"

    base_team = get_team(four_factors, base_team_name, "TeamName")
    opponent = get_team(four_factors, opponent_name, "TeamName")

    report = generate_matchup_report(base_team, opponent)

    print("Matchup loaded successfully.")
    print("Base team:", report["base_team"])
    print("Opponent:", report["opponent"])
    print("Base team identity:", report["base_team_archetype"])
    print("Opponent identity:", report["opponent_archetype"])
    print("\nScout summary:")
    print(report["matchup_summary"])

    print_section(
        "Top opponent pressure areas:",
        report["priority_opponent_pressures"],
        "No major opponent pressure areas generated by the percentile matchup engine.",
    )

    print_section(
        f"Top {report['base_team']} edge areas:",
        report["priority_base_team_edges"],
        "No major base team edge areas generated by the percentile matchup engine.",
    )

    print_section(
        "Keys to victory:",
        report["keys_to_victory"],
        "No keys generated by the matchup engine.",
    )